### ISSUE TITLE
Masks and Armor

### ISSUE THREAD

**Issue by siervua** [MalibuTechTeam/mbt_meta_clothes#1]
Would it be possible to add masks and armor to the mix as well? A lot of biker jackets are placed in the armor section, and masks would just be great to have as well.

**Comment by MalibuTechTeam** [comment]
Regarding masks were not added because in theory it is a usable item, using it you can put it on and take it off, so it is more correct so for RP purposes in case someone removes the mask item, it will automatically remove itself
