### ISSUE TITLE
When you put someone else clothes, yours are not given as item

### ISSUE THREAD

**Issue by lexinor** [MalibuTechTeam/mbt_meta_clothes#5]
To reproduce, someone is taking his shirt off, give it to you. 
Then you use their item to wear the shirt. It works but your current shirt will be override without any items in your inventory

**Comment by lexinor** [comment]
@MalibuTechTeam Any update on when it will be fixed ?

**Comment by MalibuTechTeam** [comment]
@lexinor Solved in version 1.2.0
