### ISSUE TITLE
Adding Masks?

### ISSUE THREAD

**Issue by meltynetv2** [MalibuTechTeam/mbt_meta_clothes#6]
Hello, I love the script, but I feel it is missing the masks feature to take them off as items too. Can this be added into the next update? I have it custom in my server already, but have no clue how you make the icons around the circle, so it doesn't look right.

Just a suggestion, if not no worries, just definitely something that should be added.

**Comment by MalibuTechTeam** [comment]
Hi, thanks for your suggestion, the masks the bags and other props will be added as items via a new script linked to this one we are working on. If you want to stay updated you can join our discord : https://discord.gg/tqk3kAEr4f
