### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HiTTA757** [MalibuTechTeam/mbt_meta_clothes#7]
![8B1C9539-8762-4A0D-AF0B-104E71E9386E](https://user-images.githubusercontent.com/127186414/232674008-e127db40-2af6-43c1-814a-f3a1205a2fdf.jpeg)

im not sure if it’s compatible now for qbcore but i followed  the read.me and i keep getting this error and my inventory doesn’t work.

**Comment by MalibuTechTeam** [comment]
The error showed in your screen is not related with our resource, since the items.server modules is failing to load, probably there is some error in the items declaration part, check it.
